/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'MockUSDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDC__factory>
getContractFactory(name: 'PolyPredict', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PolyPredict__factory>
getContractFactory(name: 'PoolBinaryMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PoolBinaryMarket__factory>

  getContractAt(name: 'MockUSDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDC>
getContractAt(name: 'PolyPredict', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PolyPredict>
getContractAt(name: 'PoolBinaryMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PoolBinaryMarket>

  deployContract(name: 'MockUSDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>
deployContract(name: 'PolyPredict', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PolyPredict>
deployContract(name: 'PoolBinaryMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolBinaryMarket>

  deployContract(name: 'MockUSDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>
deployContract(name: 'PolyPredict', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PolyPredict>
deployContract(name: 'PoolBinaryMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoolBinaryMarket>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  