/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PoolBinaryMarketInterface extends Interface {
    getFunction(nameOrSignature: "DECIMALS" | "MAX_PARTICIPANTS" | "MAX_STAKE_PER_USER" | "claim" | "impliedYesBps" | "noOf" | "noPoolMultiplierE4" | "outcome" | "owner" | "participantAt" | "participantCount" | "placeBet" | "renounceOwnership" | "resolve" | "resolved" | "totalNo" | "totalYes" | "transferOwnership" | "usdc" | "yesOf" | "yesPoolMultiplierE4"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BetPlaced" | "Claimed" | "MarketResolved" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'DECIMALS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_PARTICIPANTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_STAKE_PER_USER', values?: undefined): string;
encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
encodeFunctionData(functionFragment: 'impliedYesBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'noOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'noPoolMultiplierE4', values?: undefined): string;
encodeFunctionData(functionFragment: 'outcome', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'participantAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'participantCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'placeBet', values: [boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolve', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolved', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalNo', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalYes', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'yesOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'yesPoolMultiplierE4', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DECIMALS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_PARTICIPANTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_STAKE_PER_USER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'impliedYesBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'noOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'noPoolMultiplierE4', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outcome', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'participantAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'participantCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalNo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalYes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'yesOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'yesPoolMultiplierE4', data: BytesLike): Result;
  }

  
    export namespace BetPlacedEvent {
      export type InputTuple = [user: AddressLike, yesSide: boolean, amount: BigNumberish];
      export type OutputTuple = [user: string, yesSide: boolean, amount: bigint];
      export interface OutputObject {user: string, yesSide: boolean, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketResolvedEvent {
      export type InputTuple = [o: BigNumberish];
      export type OutputTuple = [o: bigint];
      export interface OutputObject {o: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PoolBinaryMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): PoolBinaryMarket;
    waitForDeployment(): Promise<this>;

    interface: PoolBinaryMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DECIMALS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_PARTICIPANTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_STAKE_PER_USER: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    impliedYesBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    noOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    noPoolMultiplierE4: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    outcome: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    participantAt: TypedContractMethod<
      [i: BigNumberish, ],
      [string],
      'view'
    >
    

    
    participantCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    placeBet: TypedContractMethod<
      [yes: boolean, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolve: TypedContractMethod<
      [o: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolved: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    totalNo: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalYes: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    yesOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    yesPoolMultiplierE4: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DECIMALS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_PARTICIPANTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_STAKE_PER_USER'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'impliedYesBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'noOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'noPoolMultiplierE4'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'outcome'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'participantAt'): TypedContractMethod<
      [i: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'participantCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'placeBet'): TypedContractMethod<
      [yes: boolean, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolve'): TypedContractMethod<
      [o: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolved'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalNo'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalYes'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'yesOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'yesPoolMultiplierE4'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'BetPlaced'): TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
getEvent(key: 'Claimed'): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
getEvent(key: 'MarketResolved'): TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'BetPlaced(address,bool,uint256)': TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
      BetPlaced: TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
    

      'Claimed(address,uint256)': TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
      Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
    

      'MarketResolved(uint8)': TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
      MarketResolved: TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }